// <auto-generated />
namespace Mittagessen.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MealVariations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MealVariations));
        
        string IMigrationMetadata.Id
        {
            get { return "201401051311131_MealVariations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
